/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 1rd.glb -T 
Files: 1rd.glb [2.01MB] > /Users/zihongchen/HackG/portfolio/public/models/1rd-transformed.glb [205.73KB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Sun1(props) {
  const { nodes, materials } = useGLTF('/models/1rd-transformed.glb')
  const material = materials["Material.002"]

  material.emissive.set("orange")
  material.emissiveIntensity = 4
  material.emissiveMap = material.map
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={material} />
    </group>
  )
}

useGLTF.preload('/models/1rd-transformed.glb')