/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 2nd.glb -T 
Files: 2nd.glb [2MB] > /Users/zihongchen/HackG/portfolio/public/models/2nd-transformed.glb [108.5KB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'


export default function Sun2(props) {
  const { nodes, materials } = useGLTF('/models/2nd-transformed.glb')
  const material = materials["Material.002"]

  material.emissive.set("orange")
  material.emissiveIntensity = 4
  material.emissiveMap = material.map
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={material}>

      </mesh>
    </group>
  )
}

useGLTF.preload('/models/2nd-transformed.glb')
