
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 2nd.glb -T 
Files: 2nd.glb [2MB] > /Users/zihongchen/HackG/portfolio/public/models/2nd-transformed.glb [108.5KB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'


export default function Sun3(props) {
  const { nodes, materials } = useGLTF('/Portfolio-Website/models/3rd-transformed.glb')
  const material = materials["Material.002"]

  material.emissive.set("yellow")
  material.emissiveIntensity = 2
  material.emissiveMap = material.map
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={material} position={[-6.714, -6.377, -3.476]} scale={2.761}/>
    </group>
  )
}

useGLTF.preload('/Portfolio-Website/models/3rd-transformed.glb')
